apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: milvus
  name: milvus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
      name: milvus-standalone
    spec:
      containers:
      - command:
        - milvus
        - run
        - standalone
        envFrom:
        - configMapRef:
            name: milconfig
        image: milvusdb/milvus:v2.4.5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9091
          initialDelaySeconds: 90
          periodSeconds: 30
        imagePullPolicy: IfNotPresent
        name: milvus
        volumeMounts:
        - mountPath: /milvus/configs
          name: embedetcd
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: milconfig
        name: milconfig
      - configMap: # Contains embedEtcd.yaml and user.yaml
          defaultMode: 420
          name: embedetcd
        name: embedetcd
      - name: datadir # To be changed to a PVC
        emptyDir:
          sizeLimit: 5Gi

