apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: milrag
  name: activitylog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
