apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: milrag
  name: milrag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milrag
  template:
    metadata:
      labels:
        app: milrag
      name: milrag-standalone
    spec:
      containers:
      #- command:
      #  - milrag
      #  - run
      #  - standalone
      - envFrom:
        - configMapRef:
            name: milconfig
        image: ksrinimba/milrag:1.1
        imagePullPolicy: IfNotPresent
        name: milrag
        #volumeMounts:
        #- mountPath: /milrag/configs
        #  name: embedetcd
      restartPolicy: Always
      #volumes:
      #- configMap:
      #    defaultMode: 420
      #    name: milconfig
      #  name: milconfig
      #- configMap: # Contains embedEtcd.yaml and user.yaml
      #    defaultMode: 420
      #    name: embedetcd
      #  name: embedetcd
      #- name: datadir # To be changed to a PVC
      #  emptyDir:
      #    sizeLimit: 5Gi

